<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>

		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<AssemblyName>CCC</AssemblyName>
		<RootNamespace>CCC</RootNamespace>

		<ApplicationManifest>app.manifest</ApplicationManifest>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="cookie.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="System.Management" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Assets\cookie.ico" />
	</ItemGroup>

</Project>